name: Bump Version
description: Action to bump the version of a project
inputs:
  pat:
    description: PAT for accessing the application repo
    required: true
  new-app-version:
    description: The new app version to bump to
    required: true
  new-chart-version:
    description: The new chart version to bump to
    required: false
    default: ""
  helm:
    description: The project uses Helm
    required: false
  node:
    description: The project uses Node
    required: false


runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ inputs.pat }}

    - name: Bump VERSION file
      run: |
        echo ${{ inputs.new-app-version }} > VERSION
      shell: bash

    - name: Bump VERSION file in chart
      if: ${{ inputs.helm && inputs.new-chart-version != '' }}
      run: |
        echo ${{ inputs.new-chart-version }} > ./charts/VERSION
      shell: bash

    - name: Bump version in helm chart
      if: ${{ inputs.helm && inputs.new-chart-version != '' }}
      # We are using sed instead of yq as yq is not preserving empty lines. See https://github.com/mikefarah/yq/issues/515
      run: |
        if [ -f "./charts/Chart.yaml" ]; then
          find . -name "./charts/Chart.yaml" -exec sed -i -E "s/version: [0-9\.]*/version: "${{ inputs.new-chart-version }}"/g" {} \;
        fi
      shell: bash

    - name: Bump appVersion in helm chart
      if: ${{ inputs.helm }}
      run: |
        if [ -f "./charts/Chart.yaml" ]; then
          find . -name "./charts/Chart.yaml" -exec sed -i -E "s/appVersion: [0-9\.]*/version: "${{ inputs.new-app-version }}"/g" {} \;
        fi
      shell: bash

    - name: Bump package.json and package-lock.json
      if: ${{ inputs.node }}
      run: |
        yq -i -j -P '.version = "${{ inputs.new-app-version }}"' 'package.json'
        if [ -f "./package-lock.json" ]; then
          yq -i -j -P '.version = "${{ inputs.new-app-version }}" | .packages[""].version = "${{ inputs.new-app-version }}"' 'package-lock.json'
        fi
      shell: bash
    
    - name: Commit Changes
      env:
        GIT_AUTHOR_NAME: Beez Innovation Labs
        GIT_COMMITTER_NAME: Beez Innovation Labs
        GIT_AUTHOR_EMAIL: github@beezlabs.com
        GIT_COMMITTER_EMAIL: github@beezlabs.com
      run: |
        git add -A
        git diff-index --quiet HEAD || git commit -m "feat: bump version to ${{ inputs.new-app-version }}"
        git push
      shell: bash
